### ISSUE TITLE
x86 dll not work

### ISSUE THREAD

**Issue by realfinder** [Asd-g/AviSynth-vsMSmooth#1]
thanks for adding new filter

I did test and note that 32 dll not work in avs 2.6 or even in avs+

here the error in avs+

![Untitled](https://user-images.githubusercontent.com/2512153/85825366-b21f7f80-b78a-11ea-8b93-06a8eefc0f1b.png)

**Comment by Asd-g** [comment]
Please redownload 1.0.0.

**Comment by realfinder** [comment]
that work now, thanks
